export const ErrorCodeEnum = {
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_USERNAME_ALREADY_EXISTS : "AUTH_USERNAME_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",

  // Access Control Errors
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",
  ACCESS_INSUFFICIENT_PERMISSION: "ACCESS_INSUFFICIENT_PERMISSION",
  ACCESS_MEMBERSHIP_REQUIRED: "ACCESS_MEMBERSHIP_REQUIRED",
  ACCESS_ROLE_ESCALATION: "ACCESS_ROLE_ESCALATION",

  // Validation and Resource Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  CHAT_CONVERSATION_NOT_FOUND: "CHAT_CONVERSATION_NOT_FOUND",
  CHAT_NOT_A_MEMBER: "CHAT_NOT_A_MEMBER",
  CHAT_DM_SELF: "CHAT_DM_SELF",
  CHAT_RATE_LIMIT: "CHAT_RATE_LIMIT",
  CHAT_INVALID_CURSOR: "CHAT_INVALID_CURSOR",

  // System Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  ACCESS_FORBIDDEN: "ACCESS_FORBIDDEN"
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;