import "dotenv/config"
import { getEnv } from "../utils/getEnv";



const appConfig = () => ({
  PORT: getEnv("PORT", "8000"),
  NODE_ENV: getEnv("NODE_ENV", "development"),
  BASE_PATH: getEnv("BASE_PATH", "/api/v1"),

  GROQ_API_KEY: getEnv("GROQ_API_KEY"),

  WHATSAPP_PHONE_NUMBER_ID: getEnv("WHATSAPP_PHONE_NUMBER_ID"),
  WHATSAPP_BUSINESS_ACCOUNT_ID : getEnv("WHATSAPP_BUSINESS_ACCOUNT_ID"),
  WHATSAPP_TOKEN : getEnv("WHATSAPP_TOKEN"),
  WHATSAPP_VERIFY_TOKEN  : getEnv("WHATSAPP_VERIFY_TOKEN"),


  PINECONE_API_KEY: getEnv("PINECONE_API_KEY"),

  DEFAULT_RESTAURANT_ID: getEnv("DEFAULT_RESTAURANT_ID", "da-pakhtun-dera"),
  USER_ACCESS_TOKEN: getEnv("USER_ACCESS_TOKEN", ""),
  OWNER_WHATSAPP_PHONE: getEnv("OWNER_WHATSAPP_PHONE", ""),
  STAFF_WHATSAPP_PHONES: getEnv("STAFF_WHATSAPP_PHONES", ""),
  DEFAULT_PREP_MINUTES: getEnv("DEFAULT_PREP_MINUTES", "30"),

  MONGO_URI: getEnv("MONGO_URI"),
  GOOGLE_GENERATIVE_AI_API_KEY: getEnv("GOOGLE_GENERATIVE_AI_API_KEY"),
  API_KEY_OF_TAVILY : getEnv("TAVILY_API_KEY"),

});



export const Env = appConfig();